config/routes.rb
MoviesLibrary::Application.routes.draw do
  root :to => 'movies#index'
  resources :movies, :only => [:index, :edit, :update, :destroy] do
    get :poster, :on => :member, :format=>/(jpg|jpeg|png|gif)/
    get :search, :on => :collection
    get :random, :on => :collection
    resources :tags,  :except => [:new, :edit, :show, :update]
  end
  
  resources :cloud, :only => [:index], :controller => "tags", :action => "cloud"

  resources :locations, :only => [:index, :create, :update, :edit, :destroy] do
    get 'scan_all', :on => :collection
    get 'scan', :on => :member
  end
  resources :admin, :only => [:index] do
    get 'delete_offline', :on => :collection
    get 'reindex', :on => :collection
    get 'export', :on => :collection    
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
	<head>
		<title>The Movies Library</title>
		<link href="http://fonts.googleapis.com/css?family=Oswald" rel="stylesheet" type="text/css" />
		<%= stylesheet_link_tag    "application", :media => "all" %>
		<%= javascript_include_tag "application" %>
		<%= csrf_meta_tags %>
		<%= yield :head %>
	</head>
	<body>
		<div id="wrapper">
			<header id="header">
				<div id="logo">
					<h1><a href="#">The Movies Library</a></h1>
				</div>
				<div id="search">
					<%= form_tag(search_movies_path, :method=> :get) do %>
					<div>
						<%= search_field_tag(:q, params[:q], :class => "form-text", :size => 32, :maxlength => 32) %>
						<%= submit_tag("Search", :class => "form-button") %>
					</div>
					<% end %>
				</div>
				<nav id="menu">
					<ul>
						<li class="first current_page_item">
							<%= link_to "Homepage", movies_path %>
						</li>
						<li>
							<%= link_to "Locations", locations_path %>
						</li>
						<li>
							<%= link_to "Administration", admin_index_path  %>
						</li>
						<li>
							<%= link_to "Random Movie", random_movies_path  %>
						</li>
						<li>
							<%= link_to "Tag Cloud", cloud_index_path  %>
						</li>
					</ul>
					<br class="clearfix" />
				</nav>
			</header>
			<div id="page">
				<div id="content">
					<h2><%= yield :title %></h2>
					<%= render 'shared/flash-messages' if !flash.empty? %>
					<%= yield %>
				</div>
				<aside id="sidebar">
					<div>
						<h3 style="display:inline;">Scan Locations</h3>
						<%= button_to("Launch", scan_all_locations_path, :form_class => "right-button", :method => :get, :confirm=> "Are you sure ?", :class => "form-button") %>
					</div>
					<br />
					<h3>Filters</h3>
					<%= form_tag(search_movies_path, :method=> :get) do %>
					<%= hidden_field_tag(:q, params[:q]) %>
					<ul class="list">
						<li class="first">
							<%= label_tag 'online', 'Online :', :class=>"filter" %>
							<%= check_box_tag(:online, true, params[:online]) %>
						</li>
						<li>
							<%= label_tag 'offline', 'Offline :', :class=>"filter" %>
							<%= check_box_tag(:offline, true, params[:offline]) %>
						</li>
						<li>
							<%= label_tag 'year_1', 'Year Range :', :class=>"filter" %>
							<%= number_field_tag(:year_1, params[:year_1], :in=>Movie.range(:year), :size=>4, :class=>"filter-text") %>
							-
							<%= number_field_tag(:year_2, params[:year_2], :in=>Movie.range(:year), :size=>4, :class=>"filter-text") %>
						</li>
						<li>
							<%= label_tag 'rank_1', 'Rank Range :', :class=>"filter" %>
							<%= number_field_tag(:rank_1, params[:rank_1], :in=>Movie.range(:rank), :size=>4, :class=>"filter-text") %>
							-
							<%= number_field_tag(:rank_2, params[:rank_2], :in=>Movie.range(:rank), :size=>4, :class=>"filter-text") %>
						</li>
						<li>
							<%= label_tag 'seen_1', 'Seen Range:', :class=>"filter" %>
							<%= number_field_tag(:seen_1, params[:seen_1], :in=>Movie.range(:seen), :size=>4, :class=>"filter-text") %>
							-
							<%= number_field_tag(:seen_2, params[:seen_2], :in=>Movie.range(:seen), :size=>4, :class=>"filter-text") %>
						</li>
						<li class="last">
							<p align="center">
								<%= submit_tag("Search", :class => "form-button right-button") %>
							</p>
						</li>
					</ul>
					<% end %>
				</aside>
				<br class="clearfix" />
			</div>
		</div>
		<footer id="footer">
			Copyright &copy; <%= Time.new.year %> Imad MANAA, All rights reserved.
		</footer>
	</body>
</html>